jwt:
  access-token-expiration: 15552000000 # 6 months
  key: ${JWT_PRIVATE_KEY}
  refresh-token-expiration: 0
logging:
  file:
    path: ./logs
  level:
    com:
      free:
        tvtracker:
          core:
            logging:
              OutRequestLoggingInterceptor: DEBUG
              RequestLoggingInterceptor: INFO
              TvtrackerLogger: DEBUG
    httpclient:
      wire: DEBUG
    org:
      apache:
        http: DEBUG
      hibernate: WARN
      springframework:
        security: DEBUG
        web: WARN
        web.client.RestTemplate: DEBUG
    root: WARN
  threshold:
    console: trace
    file: error
server:
  ssl:
    enabled: false
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: admin
    url: jdbc:postgresql://localhost:5432/tvtracker3
    username: admin2
  flyway:
    create-schemas: true
    driver-class-name: org.postgresql.Driver
    enabled: false
    group: true
    password: admin
    url: jdbc:postgresql://localhost:5432/tvtracker3
    user: admin
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
      jakarta:
        persistence:
          schema-generation:
            scripts:
              action: update
              create-source: metadata
              create-target: db_update.sql
    show-sql: true
  output:
    ansi:
      enabled: always
env-secrets:
    tmdb-key: ${TMDB_TOKEN}
