jwt:
  key: ${JWT_PRIVATE_KEY}
logging:
  file:
    path: ./logs
  level:
    com.free.tvtracker.logging.OutRequestLoggingInterceptor: INFO
    com.free.tvtracker.logging.RequestLoggingInterceptor: INFO
    com.free.tvtracker.logging.TvtrackerLogger: DEBUG
    httpclient:
      wire: off
    org:
      apache:
        http: DEBUG
      hibernate: WARN
      springframework:
        security: DEBUG
        web: WARN
        web.client.RestTemplate: DEBUG
    root: WARN
  threshold:
    console: trace
    file: error
server:
  ssl:
    enabled: false
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: admin
    url: jdbc:postgresql://localhost:5432/track8
    username: admin2
  flyway:
    create-schemas: true
    driver-class-name: org.postgresql.Driver
    enabled: false
    group: true
    password: admin
    url: jdbc:postgresql://localhost:5432/track8
    user: admin
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
      jakarta:
        persistence:
          schema-generation:
            scripts:
              action: update
              create-source: metadata
              create-target: db_update.sql
    show-sql: true
  output:
    ansi:
      enabled: always
env-secrets:
    tmdb-key: ${TMDB_TOKEN}
